version: 1.0.{build}
image: Visual Studio 2017
cache: packages -> **\packages.config
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore
build:
  project: restlessmedia.Module.File.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal